name: Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  purplemet:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: purplemet/purplemet-action@v1
        with:
          api-token: ${{ secrets.PURPLEMET_API_TOKEN }}
          base-url: 'https://api.dev.purplemet.com'
          basic-user: ${{ secrets.PPM_CLOUD_UI_BASIC_USER }}
          basic-pass: ${{ secrets.PPM_CLOUD_UI_BASIC_PASS }}
          target-url: 'https://www.epitech.eu/'
          fail-severity: 'high'
          fail-rating: 'E'
          sarif-upload: 'true'
          fail-cvss: 5
          fail-on-kev: true
          fail-on-eol: true
          fail-on-ssl: true
          fail-on-cert: true
          fail-on-headers: true
          timeout: 3000000
